package com.example.entity;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.patientID
     *
     * @mbggenerated
     */
    private String patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.mostRecentResults
     *
     * @mbggenerated
     */
    private String mostrecentresults;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.contentType
     *
     * @mbggenerated
     */
    private String contenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reportName
     *
     * @mbggenerated
     */
    private String reportname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.specificType
     *
     * @mbggenerated
     */
    private String specifictype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.documentUID
     *
     * @mbggenerated
     */
    private String documentuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.documentIdentifier
     *
     * @mbggenerated
     */
    private String documentidentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.preferredContentType
     *
     * @mbggenerated
     */
    private String preferredcontenttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.type
     *
     * @return the value of report.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.type
     *
     * @param type the value for report.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.time
     *
     * @return the value of report.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.time
     *
     * @param time the value for report.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.content
     *
     * @return the value of report.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.content
     *
     * @param content the value for report.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.patientID
     *
     * @return the value of report.patientID
     *
     * @mbggenerated
     */
    public String getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.patientID
     *
     * @param patientid the value for report.patientID
     *
     * @mbggenerated
     */
    public void setPatientid(String patientid) {
        this.patientid = patientid == null ? null : patientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.mostRecentResults
     *
     * @return the value of report.mostRecentResults
     *
     * @mbggenerated
     */
    public String getMostrecentresults() {
        return mostrecentresults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.mostRecentResults
     *
     * @param mostrecentresults the value for report.mostRecentResults
     *
     * @mbggenerated
     */
    public void setMostrecentresults(String mostrecentresults) {
        this.mostrecentresults = mostrecentresults == null ? null : mostrecentresults.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.contentType
     *
     * @return the value of report.contentType
     *
     * @mbggenerated
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.contentType
     *
     * @param contenttype the value for report.contentType
     *
     * @mbggenerated
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reportName
     *
     * @return the value of report.reportName
     *
     * @mbggenerated
     */
    public String getReportname() {
        return reportname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reportName
     *
     * @param reportname the value for report.reportName
     *
     * @mbggenerated
     */
    public void setReportname(String reportname) {
        this.reportname = reportname == null ? null : reportname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.specificType
     *
     * @return the value of report.specificType
     *
     * @mbggenerated
     */
    public String getSpecifictype() {
        return specifictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.specificType
     *
     * @param specifictype the value for report.specificType
     *
     * @mbggenerated
     */
    public void setSpecifictype(String specifictype) {
        this.specifictype = specifictype == null ? null : specifictype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.documentUID
     *
     * @return the value of report.documentUID
     *
     * @mbggenerated
     */
    public String getDocumentuid() {
        return documentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.documentUID
     *
     * @param documentuid the value for report.documentUID
     *
     * @mbggenerated
     */
    public void setDocumentuid(String documentuid) {
        this.documentuid = documentuid == null ? null : documentuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.documentIdentifier
     *
     * @return the value of report.documentIdentifier
     *
     * @mbggenerated
     */
    public String getDocumentidentifier() {
        return documentidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.documentIdentifier
     *
     * @param documentidentifier the value for report.documentIdentifier
     *
     * @mbggenerated
     */
    public void setDocumentidentifier(String documentidentifier) {
        this.documentidentifier = documentidentifier == null ? null : documentidentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.preferredContentType
     *
     * @return the value of report.preferredContentType
     *
     * @mbggenerated
     */
    public String getPreferredcontenttype() {
        return preferredcontenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.preferredContentType
     *
     * @param preferredcontenttype the value for report.preferredContentType
     *
     * @mbggenerated
     */
    public void setPreferredcontenttype(String preferredcontenttype) {
        this.preferredcontenttype = preferredcontenttype == null ? null : preferredcontenttype.trim();
    }
}