package com.example.dao;

import com.example.entity.MsgLog;
import com.example.entity.MsgLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    long countByExample(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int deleteByExample(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int insert(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int insertSelective(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    List<MsgLog> selectByExampleWithBLOBs(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    List<MsgLog> selectByExample(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    MsgLog selectByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MsgLog record, @Param("example") MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MsgLog record, @Param("example") MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MsgLog record, @Param("example") MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MsgLog record);
}