package com.example.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public ReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andPatientidIsNull() {
            addCriterion("patientID is null");
            return (Criteria) this;
        }

        public Criteria andPatientidIsNotNull() {
            addCriterion("patientID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientidEqualTo(String value) {
            addCriterion("patientID =", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotEqualTo(String value) {
            addCriterion("patientID <>", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidGreaterThan(String value) {
            addCriterion("patientID >", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidGreaterThanOrEqualTo(String value) {
            addCriterion("patientID >=", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLessThan(String value) {
            addCriterion("patientID <", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLessThanOrEqualTo(String value) {
            addCriterion("patientID <=", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLike(String value) {
            addCriterion("patientID like", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotLike(String value) {
            addCriterion("patientID not like", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidIn(List<String> values) {
            addCriterion("patientID in", values, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotIn(List<String> values) {
            addCriterion("patientID not in", values, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidBetween(String value1, String value2) {
            addCriterion("patientID between", value1, value2, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotBetween(String value1, String value2) {
            addCriterion("patientID not between", value1, value2, "patientid");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsIsNull() {
            addCriterion("mostRecentResults is null");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsIsNotNull() {
            addCriterion("mostRecentResults is not null");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsEqualTo(String value) {
            addCriterion("mostRecentResults =", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsNotEqualTo(String value) {
            addCriterion("mostRecentResults <>", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsGreaterThan(String value) {
            addCriterion("mostRecentResults >", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsGreaterThanOrEqualTo(String value) {
            addCriterion("mostRecentResults >=", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsLessThan(String value) {
            addCriterion("mostRecentResults <", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsLessThanOrEqualTo(String value) {
            addCriterion("mostRecentResults <=", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsLike(String value) {
            addCriterion("mostRecentResults like", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsNotLike(String value) {
            addCriterion("mostRecentResults not like", value, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsIn(List<String> values) {
            addCriterion("mostRecentResults in", values, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsNotIn(List<String> values) {
            addCriterion("mostRecentResults not in", values, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsBetween(String value1, String value2) {
            addCriterion("mostRecentResults between", value1, value2, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andMostrecentresultsNotBetween(String value1, String value2) {
            addCriterion("mostRecentResults not between", value1, value2, "mostrecentresults");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNull() {
            addCriterion("contentType is null");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNotNull() {
            addCriterion("contentType is not null");
            return (Criteria) this;
        }

        public Criteria andContenttypeEqualTo(String value) {
            addCriterion("contentType =", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotEqualTo(String value) {
            addCriterion("contentType <>", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThan(String value) {
            addCriterion("contentType >", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("contentType >=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThan(String value) {
            addCriterion("contentType <", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThanOrEqualTo(String value) {
            addCriterion("contentType <=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLike(String value) {
            addCriterion("contentType like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotLike(String value) {
            addCriterion("contentType not like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeIn(List<String> values) {
            addCriterion("contentType in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotIn(List<String> values) {
            addCriterion("contentType not in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeBetween(String value1, String value2) {
            addCriterion("contentType between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotBetween(String value1, String value2) {
            addCriterion("contentType not between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andReportnameIsNull() {
            addCriterion("reportName is null");
            return (Criteria) this;
        }

        public Criteria andReportnameIsNotNull() {
            addCriterion("reportName is not null");
            return (Criteria) this;
        }

        public Criteria andReportnameEqualTo(String value) {
            addCriterion("reportName =", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameNotEqualTo(String value) {
            addCriterion("reportName <>", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameGreaterThan(String value) {
            addCriterion("reportName >", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameGreaterThanOrEqualTo(String value) {
            addCriterion("reportName >=", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameLessThan(String value) {
            addCriterion("reportName <", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameLessThanOrEqualTo(String value) {
            addCriterion("reportName <=", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameLike(String value) {
            addCriterion("reportName like", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameNotLike(String value) {
            addCriterion("reportName not like", value, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameIn(List<String> values) {
            addCriterion("reportName in", values, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameNotIn(List<String> values) {
            addCriterion("reportName not in", values, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameBetween(String value1, String value2) {
            addCriterion("reportName between", value1, value2, "reportname");
            return (Criteria) this;
        }

        public Criteria andReportnameNotBetween(String value1, String value2) {
            addCriterion("reportName not between", value1, value2, "reportname");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeIsNull() {
            addCriterion("specificType is null");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeIsNotNull() {
            addCriterion("specificType is not null");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeEqualTo(String value) {
            addCriterion("specificType =", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeNotEqualTo(String value) {
            addCriterion("specificType <>", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeGreaterThan(String value) {
            addCriterion("specificType >", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeGreaterThanOrEqualTo(String value) {
            addCriterion("specificType >=", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeLessThan(String value) {
            addCriterion("specificType <", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeLessThanOrEqualTo(String value) {
            addCriterion("specificType <=", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeLike(String value) {
            addCriterion("specificType like", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeNotLike(String value) {
            addCriterion("specificType not like", value, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeIn(List<String> values) {
            addCriterion("specificType in", values, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeNotIn(List<String> values) {
            addCriterion("specificType not in", values, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeBetween(String value1, String value2) {
            addCriterion("specificType between", value1, value2, "specifictype");
            return (Criteria) this;
        }

        public Criteria andSpecifictypeNotBetween(String value1, String value2) {
            addCriterion("specificType not between", value1, value2, "specifictype");
            return (Criteria) this;
        }

        public Criteria andDocumentuidIsNull() {
            addCriterion("documentUID is null");
            return (Criteria) this;
        }

        public Criteria andDocumentuidIsNotNull() {
            addCriterion("documentUID is not null");
            return (Criteria) this;
        }

        public Criteria andDocumentuidEqualTo(String value) {
            addCriterion("documentUID =", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidNotEqualTo(String value) {
            addCriterion("documentUID <>", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidGreaterThan(String value) {
            addCriterion("documentUID >", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidGreaterThanOrEqualTo(String value) {
            addCriterion("documentUID >=", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidLessThan(String value) {
            addCriterion("documentUID <", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidLessThanOrEqualTo(String value) {
            addCriterion("documentUID <=", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidLike(String value) {
            addCriterion("documentUID like", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidNotLike(String value) {
            addCriterion("documentUID not like", value, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidIn(List<String> values) {
            addCriterion("documentUID in", values, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidNotIn(List<String> values) {
            addCriterion("documentUID not in", values, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidBetween(String value1, String value2) {
            addCriterion("documentUID between", value1, value2, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentuidNotBetween(String value1, String value2) {
            addCriterion("documentUID not between", value1, value2, "documentuid");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierIsNull() {
            addCriterion("documentIdentifier is null");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierIsNotNull() {
            addCriterion("documentIdentifier is not null");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierEqualTo(String value) {
            addCriterion("documentIdentifier =", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierNotEqualTo(String value) {
            addCriterion("documentIdentifier <>", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierGreaterThan(String value) {
            addCriterion("documentIdentifier >", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierGreaterThanOrEqualTo(String value) {
            addCriterion("documentIdentifier >=", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierLessThan(String value) {
            addCriterion("documentIdentifier <", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierLessThanOrEqualTo(String value) {
            addCriterion("documentIdentifier <=", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierLike(String value) {
            addCriterion("documentIdentifier like", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierNotLike(String value) {
            addCriterion("documentIdentifier not like", value, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierIn(List<String> values) {
            addCriterion("documentIdentifier in", values, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierNotIn(List<String> values) {
            addCriterion("documentIdentifier not in", values, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierBetween(String value1, String value2) {
            addCriterion("documentIdentifier between", value1, value2, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andDocumentidentifierNotBetween(String value1, String value2) {
            addCriterion("documentIdentifier not between", value1, value2, "documentidentifier");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeIsNull() {
            addCriterion("preferredContentType is null");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeIsNotNull() {
            addCriterion("preferredContentType is not null");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeEqualTo(String value) {
            addCriterion("preferredContentType =", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeNotEqualTo(String value) {
            addCriterion("preferredContentType <>", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeGreaterThan(String value) {
            addCriterion("preferredContentType >", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("preferredContentType >=", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeLessThan(String value) {
            addCriterion("preferredContentType <", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeLessThanOrEqualTo(String value) {
            addCriterion("preferredContentType <=", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeLike(String value) {
            addCriterion("preferredContentType like", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeNotLike(String value) {
            addCriterion("preferredContentType not like", value, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeIn(List<String> values) {
            addCriterion("preferredContentType in", values, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeNotIn(List<String> values) {
            addCriterion("preferredContentType not in", values, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeBetween(String value1, String value2) {
            addCriterion("preferredContentType between", value1, value2, "preferredcontenttype");
            return (Criteria) this;
        }

        public Criteria andPreferredcontenttypeNotBetween(String value1, String value2) {
            addCriterion("preferredContentType not between", value1, value2, "preferredcontenttype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}